
db.createCollection( 'paseos', {validator: {$jsonSchema: {bsonType: 'object',description:'Almacena los paseos con toda su información',title:'paseos',required: [         'idCreador',          'nombre',          'fechaCreacion',          'fechaPaseo',          'esCompartido',          'destino',          'seccionRestaurantes'],properties: {idCreador: {bsonType: 'objectId'},nombre: {bsonType: 'string'},fechaCreacion: {bsonType: 'date'},fechaPaseo: {bsonType: 'date'},pinPaseo: {bsonType: 'int'},esCompartido: {bsonType: 'bool'},destino: {bsonType: 'object',
title:'destino',required: [         'nombre',          'urlFotosDestino',          'pais',          'idLugarGoogle',          'descripcion'],properties: {nombre: {bsonType: 'string'},urlFotosDestino: {bsonType: 'array',items: {bsonType: 'string'}},pais: {bsonType: 'string'},idLugarGoogle: {bsonType: 'string'},descripcion: {bsonType: 'string'}}},seccionRestaurantes: {bsonType: 'object',
title:'seccionRestaurantes',required: [         'esFinalizadasVotaciones',          'restaurantes'],properties: {esFinalizadasVotaciones: {bsonType: 'bool'},fechaFinalizacionVotaciones: {bsonType: 'date'},restaurantes: {bsonType: 'array',items: {
title:'lugar',required: [         'nombre',          'urlFotos',          'descripcion',          'idLugarGoogle',          'votaciones'],properties: {nombre: {bsonType: 'string'},urlFotos: {bsonType: 'array',items: {bsonType: 'string'}},descripcion: {bsonType: 'string'},rangoPrecios: {bsonType: 'string'},idLugarGoogle: {bsonType: 'string'},votaciones: {bsonType: 'array',items: {
title:'votacion',required: [         'idVotante',          'fecha',          'resultado'],properties: {idVotante: {bsonType: 'objectId'},fecha: {bsonType: 'date'},resultado: {bsonType: 'bool'}}}}}}}}},seccionAtraccionesTuristicas: {bsonType: 'object',
title:'seccionAtraccionesTuristicas',required: [         'esFinalizadasVotaciones',          'atraccionesturisticas'],properties: {esFinalizadasVotaciones: {bsonType: 'bool'},fechaFinalizacionVotaciones: {bsonType: 'date'},atraccionesturisticas: {bsonType: 'array',items: {
title:'lugar',required: [         'nombre',          'urlFotos',          'descripcion',          'idLugarGoogle',          'votaciones'],properties: {nombre: {bsonType: 'string'},urlFotos: {bsonType: 'array',items: {bsonType: 'string'}},descripcion: {bsonType: 'string'},rangoPrecios: {bsonType: 'string'},idLugarGoogle: {bsonType: 'string'},votaciones: {bsonType: 'array',items: {
title:'votacion',required: [         'idVotante',          'fecha',          'resultado'],properties: {idVotante: {bsonType: 'objectId'},fecha: {bsonType: 'date'},resultado: {bsonType: 'bool'}}}}}}}}},integrantes: {bsonType: 'array',items: {
title:'integrante',required: [         'idIntegrante',          'fechaIntegracion',          'esConfirmadaAsistencia'],properties: {idIntegrante: {bsonType: 'objectId'},fechaIntegracion: {bsonType: 'date'},esConfirmadaAsistencia: {bsonType: 'bool'}}}}}         }      },
autoIndexId:true
});  